/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrintOriginal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrintOriginal{}

// PrintOriginal struct for PrintOriginal
type PrintOriginal struct {
	Url *string `json:"url,omitempty"`
	Width *string `json:"width,omitempty"`
	Height *string `json:"height,omitempty"`
}

// NewPrintOriginal instantiates a new PrintOriginal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrintOriginal() *PrintOriginal {
	this := PrintOriginal{}
	return &this
}

// NewPrintOriginalWithDefaults instantiates a new PrintOriginal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintOriginalWithDefaults() *PrintOriginal {
	this := PrintOriginal{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PrintOriginal) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintOriginal) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PrintOriginal) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PrintOriginal) SetUrl(v string) {
	o.Url = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *PrintOriginal) GetWidth() string {
	if o == nil || IsNil(o.Width) {
		var ret string
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintOriginal) GetWidthOk() (*string, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *PrintOriginal) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given string and assigns it to the Width field.
func (o *PrintOriginal) SetWidth(v string) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *PrintOriginal) GetHeight() string {
	if o == nil || IsNil(o.Height) {
		var ret string
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintOriginal) GetHeightOk() (*string, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *PrintOriginal) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given string and assigns it to the Height field.
func (o *PrintOriginal) SetHeight(v string) {
	o.Height = &v
}

func (o PrintOriginal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrintOriginal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	return toSerialize, nil
}

type NullablePrintOriginal struct {
	value *PrintOriginal
	isSet bool
}

func (v NullablePrintOriginal) Get() *PrintOriginal {
	return v.value
}

func (v *NullablePrintOriginal) Set(val *PrintOriginal) {
	v.value = val
	v.isSet = true
}

func (v NullablePrintOriginal) IsSet() bool {
	return v.isSet
}

func (v *NullablePrintOriginal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrintOriginal(val *PrintOriginal) *NullablePrintOriginal {
	return &NullablePrintOriginal{value: val, isSet: true}
}

func (v NullablePrintOriginal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrintOriginal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


