/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CategoryChildren type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryChildren{}

// CategoryChildren struct for CategoryChildren
type CategoryChildren struct {
	TotalCount *int32 `json:"total_count,omitempty"`
	Items []CategoryChildrenItemsInner `json:"items,omitempty"`
}

// NewCategoryChildren instantiates a new CategoryChildren object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryChildren() *CategoryChildren {
	this := CategoryChildren{}
	return &this
}

// NewCategoryChildrenWithDefaults instantiates a new CategoryChildren object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryChildrenWithDefaults() *CategoryChildren {
	this := CategoryChildren{}
	return &this
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *CategoryChildren) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryChildren) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *CategoryChildren) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *CategoryChildren) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CategoryChildren) GetItems() []CategoryChildrenItemsInner {
	if o == nil || IsNil(o.Items) {
		var ret []CategoryChildrenItemsInner
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryChildren) GetItemsOk() ([]CategoryChildrenItemsInner, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CategoryChildren) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CategoryChildrenItemsInner and assigns it to the Items field.
func (o *CategoryChildren) SetItems(v []CategoryChildrenItemsInner) {
	o.Items = v
}

func (o CategoryChildren) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryChildren) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCategoryChildren struct {
	value *CategoryChildren
	isSet bool
}

func (v NullableCategoryChildren) Get() *CategoryChildren {
	return v.value
}

func (v *NullableCategoryChildren) Set(val *CategoryChildren) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryChildren) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryChildren) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryChildren(val *CategoryChildren) *NullableCategoryChildren {
	return &NullableCategoryChildren{value: val, isSet: true}
}

func (v NullableCategoryChildren) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryChildren) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


