/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileUploadStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileUploadStatus{}

// FileUploadStatus struct for FileUploadStatus
type FileUploadStatus struct {
	UploadId *string `json:"upload_id,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewFileUploadStatus instantiates a new FileUploadStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileUploadStatus() *FileUploadStatus {
	this := FileUploadStatus{}
	return &this
}

// NewFileUploadStatusWithDefaults instantiates a new FileUploadStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileUploadStatusWithDefaults() *FileUploadStatus {
	this := FileUploadStatus{}
	return &this
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *FileUploadStatus) GetUploadId() string {
	if o == nil || IsNil(o.UploadId) {
		var ret string
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUploadStatus) GetUploadIdOk() (*string, bool) {
	if o == nil || IsNil(o.UploadId) {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *FileUploadStatus) HasUploadId() bool {
	if o != nil && !IsNil(o.UploadId) {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given string and assigns it to the UploadId field.
func (o *FileUploadStatus) SetUploadId(v string) {
	o.UploadId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *FileUploadStatus) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUploadStatus) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *FileUploadStatus) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *FileUploadStatus) SetFilename(v string) {
	o.Filename = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FileUploadStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUploadStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FileUploadStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FileUploadStatus) SetStatus(v string) {
	o.Status = &v
}

func (o FileUploadStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileUploadStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UploadId) {
		toSerialize["upload_id"] = o.UploadId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableFileUploadStatus struct {
	value *FileUploadStatus
	isSet bool
}

func (v NullableFileUploadStatus) Get() *FileUploadStatus {
	return v.value
}

func (v *NullableFileUploadStatus) Set(val *FileUploadStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableFileUploadStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableFileUploadStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileUploadStatus(val *FileUploadStatus) *NullableFileUploadStatus {
	return &NullableFileUploadStatus{value: val, isSet: true}
}

func (v NullableFileUploadStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileUploadStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


