/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilePost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilePost201Response{}

// FilePost201Response struct for FilePost201Response
type FilePost201Response struct {
	Filename *string `json:"filename,omitempty"`
}

// NewFilePost201Response instantiates a new FilePost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilePost201Response() *FilePost201Response {
	this := FilePost201Response{}
	return &this
}

// NewFilePost201ResponseWithDefaults instantiates a new FilePost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilePost201ResponseWithDefaults() *FilePost201Response {
	this := FilePost201Response{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *FilePost201Response) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilePost201Response) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *FilePost201Response) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *FilePost201Response) SetFilename(v string) {
	o.Filename = &v
}

func (o FilePost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilePost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	return toSerialize, nil
}

type NullableFilePost201Response struct {
	value *FilePost201Response
	isSet bool
}

func (v NullableFilePost201Response) Get() *FilePost201Response {
	return v.value
}

func (v *NullableFilePost201Response) Set(val *FilePost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFilePost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFilePost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilePost201Response(val *FilePost201Response) *NullableFilePost201Response {
	return &NullableFilePost201Response{value: val, isSet: true}
}

func (v NullableFilePost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilePost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


