/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ImageUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageUploadRequest{}

// ImageUploadRequest struct for ImageUploadRequest
type ImageUploadRequest struct {
	Filename *string `json:"filename,omitempty"`
	Size *int32 `json:"size,omitempty"`
}

// NewImageUploadRequest instantiates a new ImageUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUploadRequest() *ImageUploadRequest {
	this := ImageUploadRequest{}
	return &this
}

// NewImageUploadRequestWithDefaults instantiates a new ImageUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUploadRequestWithDefaults() *ImageUploadRequest {
	this := ImageUploadRequest{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *ImageUploadRequest) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadRequest) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *ImageUploadRequest) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *ImageUploadRequest) SetFilename(v string) {
	o.Filename = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ImageUploadRequest) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadRequest) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ImageUploadRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ImageUploadRequest) SetSize(v int32) {
	o.Size = &v
}

func (o ImageUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableImageUploadRequest struct {
	value *ImageUploadRequest
	isSet bool
}

func (v NullableImageUploadRequest) Get() *ImageUploadRequest {
	return v.value
}

func (v *NullableImageUploadRequest) Set(val *ImageUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUploadRequest(val *ImageUploadRequest) *NullableImageUploadRequest {
	return &NullableImageUploadRequest{value: val, isSet: true}
}

func (v NullableImageUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


