/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Print type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Print{}

// Print struct for Print
type Print struct {
	Id *int32 `json:"id,omitempty"`
	Original *PrintOriginal `json:"original,omitempty"`
	Thumbnail *PrintOriginal `json:"thumbnail,omitempty"`
	Standard *PrintOriginal `json:"standard,omitempty"`
}

// NewPrint instantiates a new Print object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrint() *Print {
	this := Print{}
	return &this
}

// NewPrintWithDefaults instantiates a new Print object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintWithDefaults() *Print {
	this := Print{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Print) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Print) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Print) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Print) SetId(v int32) {
	o.Id = &v
}

// GetOriginal returns the Original field value if set, zero value otherwise.
func (o *Print) GetOriginal() PrintOriginal {
	if o == nil || IsNil(o.Original) {
		var ret PrintOriginal
		return ret
	}
	return *o.Original
}

// GetOriginalOk returns a tuple with the Original field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Print) GetOriginalOk() (*PrintOriginal, bool) {
	if o == nil || IsNil(o.Original) {
		return nil, false
	}
	return o.Original, true
}

// HasOriginal returns a boolean if a field has been set.
func (o *Print) HasOriginal() bool {
	if o != nil && !IsNil(o.Original) {
		return true
	}

	return false
}

// SetOriginal gets a reference to the given PrintOriginal and assigns it to the Original field.
func (o *Print) SetOriginal(v PrintOriginal) {
	o.Original = &v
}

// GetThumbnail returns the Thumbnail field value if set, zero value otherwise.
func (o *Print) GetThumbnail() PrintOriginal {
	if o == nil || IsNil(o.Thumbnail) {
		var ret PrintOriginal
		return ret
	}
	return *o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Print) GetThumbnailOk() (*PrintOriginal, bool) {
	if o == nil || IsNil(o.Thumbnail) {
		return nil, false
	}
	return o.Thumbnail, true
}

// HasThumbnail returns a boolean if a field has been set.
func (o *Print) HasThumbnail() bool {
	if o != nil && !IsNil(o.Thumbnail) {
		return true
	}

	return false
}

// SetThumbnail gets a reference to the given PrintOriginal and assigns it to the Thumbnail field.
func (o *Print) SetThumbnail(v PrintOriginal) {
	o.Thumbnail = &v
}

// GetStandard returns the Standard field value if set, zero value otherwise.
func (o *Print) GetStandard() PrintOriginal {
	if o == nil || IsNil(o.Standard) {
		var ret PrintOriginal
		return ret
	}
	return *o.Standard
}

// GetStandardOk returns a tuple with the Standard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Print) GetStandardOk() (*PrintOriginal, bool) {
	if o == nil || IsNil(o.Standard) {
		return nil, false
	}
	return o.Standard, true
}

// HasStandard returns a boolean if a field has been set.
func (o *Print) HasStandard() bool {
	if o != nil && !IsNil(o.Standard) {
		return true
	}

	return false
}

// SetStandard gets a reference to the given PrintOriginal and assigns it to the Standard field.
func (o *Print) SetStandard(v PrintOriginal) {
	o.Standard = &v
}

func (o Print) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Print) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Original) {
		toSerialize["original"] = o.Original
	}
	if !IsNil(o.Thumbnail) {
		toSerialize["thumbnail"] = o.Thumbnail
	}
	if !IsNil(o.Standard) {
		toSerialize["standard"] = o.Standard
	}
	return toSerialize, nil
}

type NullablePrint struct {
	value *Print
	isSet bool
}

func (v NullablePrint) Get() *Print {
	return v.value
}

func (v *NullablePrint) Set(val *Print) {
	v.value = val
	v.isSet = true
}

func (v NullablePrint) IsSet() bool {
	return v.isSet
}

func (v *NullablePrint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrint(val *Print) *NullablePrint {
	return &NullablePrint{value: val, isSet: true}
}

func (v NullablePrint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


