/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ImageUploadStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageUploadStatus{}

// ImageUploadStatus struct for ImageUploadStatus
type ImageUploadStatus struct {
	UploadId *string `json:"upload_id,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewImageUploadStatus instantiates a new ImageUploadStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUploadStatus() *ImageUploadStatus {
	this := ImageUploadStatus{}
	return &this
}

// NewImageUploadStatusWithDefaults instantiates a new ImageUploadStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUploadStatusWithDefaults() *ImageUploadStatus {
	this := ImageUploadStatus{}
	return &this
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *ImageUploadStatus) GetUploadId() string {
	if o == nil || IsNil(o.UploadId) {
		var ret string
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadStatus) GetUploadIdOk() (*string, bool) {
	if o == nil || IsNil(o.UploadId) {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *ImageUploadStatus) HasUploadId() bool {
	if o != nil && !IsNil(o.UploadId) {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given string and assigns it to the UploadId field.
func (o *ImageUploadStatus) SetUploadId(v string) {
	o.UploadId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *ImageUploadStatus) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadStatus) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *ImageUploadStatus) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *ImageUploadStatus) SetFilename(v string) {
	o.Filename = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ImageUploadStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ImageUploadStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ImageUploadStatus) SetStatus(v string) {
	o.Status = &v
}

func (o ImageUploadStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageUploadStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UploadId) {
		toSerialize["upload_id"] = o.UploadId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableImageUploadStatus struct {
	value *ImageUploadStatus
	isSet bool
}

func (v NullableImageUploadStatus) Get() *ImageUploadStatus {
	return v.value
}

func (v *NullableImageUploadStatus) Set(val *ImageUploadStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUploadStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUploadStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUploadStatus(val *ImageUploadStatus) *NullableImageUploadStatus {
	return &NullableImageUploadStatus{value: val, isSet: true}
}

func (v NullableImageUploadStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUploadStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


