/*
MyMiniFactory API

3D printable object API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ImageUploadId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageUploadId{}

// ImageUploadId struct for ImageUploadId
type ImageUploadId struct {
	UploadId *string `json:"upload_id,omitempty"`
	Filename *string `json:"filename,omitempty"`
}

// NewImageUploadId instantiates a new ImageUploadId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUploadId() *ImageUploadId {
	this := ImageUploadId{}
	return &this
}

// NewImageUploadIdWithDefaults instantiates a new ImageUploadId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUploadIdWithDefaults() *ImageUploadId {
	this := ImageUploadId{}
	return &this
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *ImageUploadId) GetUploadId() string {
	if o == nil || IsNil(o.UploadId) {
		var ret string
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadId) GetUploadIdOk() (*string, bool) {
	if o == nil || IsNil(o.UploadId) {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *ImageUploadId) HasUploadId() bool {
	if o != nil && !IsNil(o.UploadId) {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given string and assigns it to the UploadId field.
func (o *ImageUploadId) SetUploadId(v string) {
	o.UploadId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *ImageUploadId) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUploadId) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *ImageUploadId) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *ImageUploadId) SetFilename(v string) {
	o.Filename = &v
}

func (o ImageUploadId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageUploadId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UploadId) {
		toSerialize["upload_id"] = o.UploadId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	return toSerialize, nil
}

type NullableImageUploadId struct {
	value *ImageUploadId
	isSet bool
}

func (v NullableImageUploadId) Get() *ImageUploadId {
	return v.value
}

func (v *NullableImageUploadId) Set(val *ImageUploadId) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUploadId) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUploadId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUploadId(val *ImageUploadId) *NullableImageUploadId {
	return &NullableImageUploadId{value: val, isSet: true}
}

func (v NullableImageUploadId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUploadId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


